spring:
    application:
        name: dicovery-service

server:
    port: 8761

eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
    instance:
        prefer-ip-address: true
        hostname: localhost